### ISSUE TITLE
DNS TXT record not outputting in the console? after running the command?

### ISSUE THREAD

**Issue by flexpeace** [fastly/heroku-fastly#21]

**Comment by andriantoniades** [comment]
Hi @flexpeace ! Thank you for letting us know about this. Could you please send an email to support@fastly.com, and include the exact command you used and any output that did appear in your terminal as a result? We'll be happy to take a look.

**Comment by evrowe** [comment]
Hi @flexpeace, this issue should now be fixed. If you have any more trouble, please open a support ticket with Heroku to help get things resolved.
