### ISSUE TITLE
Could not @fastly/heroku-plugin, returned 404

### ISSUE THREAD

**Issue by shibuyamio** [fastly/heroku-fastly#29]
When trying to install  @fastly/heroku-plugin, npm returns 404 and fail to install plugin.

```
heroku plugins:install @fastly/heroku-plugin
error An unexpected error occurred: "https://registry.npmjs.org/@fastly%2fheroku-plugin: Not found".
Installing plugin @fastly/heroku-plugin... !
Error: yarn add @fastly/heroku-plugin@latest --non-interactive --mutex=file:/Users/shibuya/.local/share/heroku/yarn.lock --preferred-cache-folder=/Users/shibuya/Library/Caches/heroku/yarn --check-files --registry=https://registry.npmjs.org exited with code 1
    at ChildProcess.forked.on (/usr/local/Cellar/heroku/7.7.8/lib/client/7.18.4/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)
```
How can I solve this issue?

**Comment by hobara** [comment]
Could you try the following commands?

- `git clone https://github.com/fastly/heroku-fastly.git`
- `cd heroku-fastly/`
- `npm install`
- `heroku plugins:link`

`heroku plugins` should list `@fastly/heroku-plugin` upon the installation.

**Comment by nettum** [comment]
I'm getting the same error.
```
➜ heroku plugins:install @fastly/heroku-plugin
error An unexpected error occurred: "https://registry.npmjs.org/@fastly%2fheroku-plugin: Not found".
Installing plugin @fastly/heroku-plugin... !
Error: yarn add @fastly/heroku-plugin@latest --non-interactive --mutex=file:/home/nettum/.local/share/heroku/yarn.lock --preferred-cache-folder=/home/nettum/.cache/heroku/yarn --check-files --registry=https://registry.npmjs.org exited with code 1
    at ChildProcess.forked.on (/usr/lib/heroku/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)

```

When I try to navigate with my browser to https://www.npmjs.com/package/@fastly/heroku-plugin I only get to the npmjs login page.

I can get to https://www.npmjs.com/package/heroku-fastly page, but as the readme says it's depricated in favour to @fastly/heroku-plugin

**Comment by evrowe** [comment]
Hi @shibuyamio, @hobara, @nettum!

Thanks for reporting this issue. It seems we had a slight hitch when we migrated this package to the `@fastly` namespace on npm. We've adjusted the access settings and you _should_ be able to install it as expected now. Would you mind verifying and letting us know?

**Comment by nettum** [comment]
Thanks!
Seems fine now! :+1: 
```
➜ heroku plugins:install @fastly/heroku-plugin
Installing plugin @fastly/heroku-plugin... installed v2.0.0
➜ heroku plugins
@fastly/heroku-plugin 2.0.0

```

**Comment by evrowe** [comment]
Great, thanks for confirming!
